razorpay.api.key=rzp_test_dummykey123
razorpay.api.secret=dummysecret456

cloudinary.api.name=dummyname
cloudinary.api.key=dummykey
cloudinary.api.secret=dummysecret

spring.application.name=ecommerce


spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=silas@gmail.com
spring.mail.password=Silas@1123$

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true